"use client";

import { useActionState, useMemo, useRef, useTransition } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { ClapperboardIcon, ShieldCheckIcon } from "lucide-react";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty";
import { Field, FieldDescription, FieldError, FieldGroup, FieldLabel, FieldLegend, FieldSet } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Spinner } from "@/components/ui/spinner";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { createVideoProjectAction, initialVideoActionState } from "@/lib/actions/video";
import { videoProjectDraftFormSchema } from "@/lib/form-schemas";
import type { ReadyVideoProductSource, VideoWorkspaceEntry } from "@/lib/video/store";

type Values = z.infer<typeof videoProjectDraftFormSchema>;
type FormValues = z.input<typeof videoProjectDraftFormSchema>;
const platforms = [{ value: "youtube", label: "YouTube" }, { value: "tiktok", label: "TikTok" }, { value: "instagram", label: "Instagram" }, { value: "facebook", label: "Facebook" }, { value: "x", label: "X" }] as const;

function stateLabel(state: string) { return ({ VIDEO_REVIEW_REQUIRED: "待 Gate 01 审核", VIDEO_APPROVED: "已批准", VIDEO_REVISION_REQUIRED: "待修订", VIDEO_EXPORT_READY: "可导出" } as Record<string, string>)[state] ?? state; }

export function VideoWorkspacePanel({ products, entries }: { products: ReadyVideoProductSource[]; entries: VideoWorkspaceEntry[] }) {
  const [state, action, pending] = useActionState(createVideoProjectAction, initialVideoActionState);
  const [, startTransition] = useTransition();
  const formElement = useRef<HTMLFormElement>(null); const assetInput = useRef<HTMLInputElement>(null);
  const form = useForm<FormValues, unknown, Values>({ resolver: zodResolver(videoProjectDraftFormSchema), defaultValues: { productId: "", factPath: "", objective: "", targetAudience: "", scenePrompt: "", durationSeconds: 5, platforms: ["youtube", "tiktok"], assetRef: "", rightsEvidenceRef: "" } });
  const productId = form.watch("productId"); const chosen = useMemo(() => products.find((product) => product.id === productId), [products, productId]);
  function onSubmit(values: Values) { const data = new FormData(formElement.current ?? undefined); for (const [key, value] of Object.entries(values)) { data.delete(key); if (key === "platforms" && Array.isArray(value)) for (const platform of value) data.append("platforms", platform); else data.set(key, String(value)); } startTransition(() => action(data)); }
  function receiveAssets(files: FileList) { const transfer = new DataTransfer(); for (const file of Array.from(files)) transfer.items.add(file); if (assetInput.current) assetInput.current.files = transfer.files; }
  return <div className="mx-auto flex min-h-full w-full max-w-7xl flex-col gap-6 p-4 md:p-6 lg:p-8">
    <header className="flex flex-col gap-2"><div className="flex flex-wrap gap-2"><Badge variant="secondary">营销视频资料入口</Badge><Badge variant="outline">仅创建审核项目</Badge></div><h1 className="text-3xl font-semibold tracking-tight text-balance">资料、文案与视觉素材，一次组成营销视频计划</h1><p className="max-w-3xl text-muted-foreground text-pretty">先在 Product Agent 拖入产品资料并通过 Gate 01；这里再补充营销文案与私有图片/视频素材。项目创建不会选择模型、发送资料、生成视频或发布到社交媒体。</p></header>
    <Alert><ShieldCheckIcon /><AlertTitle>工程事实与素材权利必须可追溯</AlertTitle><AlertDescription>选择的字段必须已绑定产品证据；素材与权利证明仅保存为脱敏私有引用。人工 Gate 01 通过前不能进入导出准备。</AlertDescription></Alert>
    {products.length === 0 ? <Empty><EmptyHeader><EmptyMedia variant="icon"><ClapperboardIcon /></EmptyMedia><EmptyTitle>先拖入产品资料</EmptyTitle><EmptyDescription>在 Product Agent 上传 PDF、CSV 或表格资料并完成 Gate 01 后，可在这里把已核验事实与营销素材组成视频计划。</EmptyDescription></EmptyHeader><EmptyContent>视频工作台不会接受草稿产品或手工填写的工程事实。</EmptyContent></Empty> : <Card><CardHeader><CardTitle>新建待审营销视频计划</CardTitle><CardDescription>选取已核验事实，补充营销文案和可选视觉素材，再交由人工审核。渠道勾选只声明目标，不会触发发布。</CardDescription></CardHeader><CardContent><form ref={formElement} autoComplete="off" onSubmit={form.handleSubmit(onSubmit)}><FieldGroup>
      <Field data-invalid={!!form.formState.errors.productId}><FieldLabel htmlFor="video-product">已核验产品</FieldLabel><Controller control={form.control} name="productId" render={({ field }) => <Select items={products.map((product) => ({ value: product.id, label: `${product.internalSku} · ${product.productName}` }))} value={field.value} onValueChange={(value) => { field.onChange(value); form.setValue("factPath", ""); }}><SelectTrigger id="video-product" className="w-full" aria-invalid={!!form.formState.errors.productId}><SelectValue placeholder="选择已核验产品" /></SelectTrigger><SelectContent><SelectGroup>{products.map((product) => <SelectItem key={product.id} value={product.id}>{product.internalSku} · {product.productName}</SelectItem>)}</SelectGroup></SelectContent></Select>} /><FieldError>{form.formState.errors.productId?.message}</FieldError></Field>
      <Field data-invalid={!!form.formState.errors.factPath}><FieldLabel htmlFor="video-fact">已验证的事实字段</FieldLabel><Controller control={form.control} name="factPath" render={({ field }) => <Select items={chosen?.factOptions ?? []} value={field.value} onValueChange={field.onChange} disabled={!chosen}><SelectTrigger id="video-fact" className="w-full" aria-invalid={!!form.formState.errors.factPath}><SelectValue placeholder={chosen ? "选择可引用字段" : "先选择产品"} /></SelectTrigger><SelectContent><SelectGroup>{chosen?.factOptions.map((option) => <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectGroup></SelectContent></Select>} /><FieldDescription>服务端会重新读取字段值与证据，不采纳浏览器传入的产品值。</FieldDescription><FieldError>{form.formState.errors.factPath?.message}</FieldError></Field>
      <Field data-invalid={!!form.formState.errors.objective}><FieldLabel htmlFor="video-objective">营销目标</FieldLabel><Input id="video-objective" aria-invalid={!!form.formState.errors.objective} {...form.register("objective")} /><FieldError>{form.formState.errors.objective?.message}</FieldError></Field>
      <Field data-invalid={!!form.formState.errors.targetAudience}><FieldLabel htmlFor="video-audience">目标受众</FieldLabel><Input id="video-audience" aria-invalid={!!form.formState.errors.targetAudience} {...form.register("targetAudience")} /><FieldError>{form.formState.errors.targetAudience?.message}</FieldError></Field>
      <Field data-invalid={!!form.formState.errors.scenePrompt}><FieldLabel htmlFor="video-prompt">营销文案与镜头说明</FieldLabel><Textarea id="video-prompt" aria-invalid={!!form.formState.errors.scenePrompt} {...form.register("scenePrompt")} /><FieldDescription>说明镜头表现，不得添加未绑定证据的 OE、尺寸、材料、认证、寿命或安全事实。</FieldDescription><FieldError>{form.formState.errors.scenePrompt?.message}</FieldError></Field>
      <Field data-invalid={!!form.formState.errors.durationSeconds}><FieldLabel htmlFor="video-duration">镜头时长（秒）</FieldLabel><Input id="video-duration" type="number" min={1} max={30} aria-invalid={!!form.formState.errors.durationSeconds} {...form.register("durationSeconds", { valueAsNumber: true })} /><FieldError>{form.formState.errors.durationSeconds?.message}</FieldError></Field>
      <FieldSet><FieldLegend>目标平台</FieldLegend><FieldDescription>仅作为输出意图记录；未核验平台仍会在导出阶段拒绝。</FieldDescription><FieldGroup>{platforms.map((platform) => <Controller key={platform.value} control={form.control} name="platforms" render={({ field }) => <Field orientation="horizontal"><Checkbox id={`video-platform-${platform.value}`} checked={field.value.includes(platform.value)} onCheckedChange={(checked) => field.onChange(checked ? [...field.value, platform.value] : field.value.filter((value) => value !== platform.value))} /><FieldLabel htmlFor={`video-platform-${platform.value}`}>{platform.label}</FieldLabel></Field>} />)}</FieldGroup><FieldError>{form.formState.errors.platforms?.message}</FieldError></FieldSet>
      <Field onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); receiveAssets(event.dataTransfer.files); }}><FieldLabel htmlFor="video-assets">拖入或选择视觉素材（可选）</FieldLabel><Input ref={assetInput} id="video-assets" name="assets" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/quicktime" multiple /><FieldDescription>支持 JPG、PNG、WebP、MP4、MOV；最多 8 个文件，总计不超过 20MB。素材只保存到私有存储，不会在此阶段发送给生成模型。</FieldDescription></Field>
      <Field data-invalid={!!form.formState.errors.assetRef}><FieldLabel htmlFor="video-asset">已有私有素材引用（可选）</FieldLabel><Input id="video-asset" placeholder="asset-product-001" aria-invalid={!!form.formState.errors.assetRef} {...form.register("assetRef")} /><FieldDescription>已存入系统的素材可直接引用；不上传视觉素材时可留空，以文案创建文本生成视频计划。</FieldDescription><FieldError>{form.formState.errors.assetRef?.message}</FieldError></Field>
      <Field data-invalid={!!form.formState.errors.rightsEvidenceRef}><FieldLabel htmlFor="video-rights">素材权利证据引用</FieldLabel><Input id="video-rights" placeholder="evidence-rights-001" aria-invalid={!!form.formState.errors.rightsEvidenceRef} {...form.register("rightsEvidenceRef")} /><FieldDescription>上传或引用视觉素材时必填；只使用文案时可留空。</FieldDescription><FieldError>{form.formState.errors.rightsEvidenceRef?.message}</FieldError></Field>
    </FieldGroup></form></CardContent><CardFooter className="flex flex-col items-start gap-3"><Button type="button" disabled={pending} onClick={form.handleSubmit(onSubmit)}>{pending ? <Spinner data-icon="inline-start" /> : <ClapperboardIcon data-icon="inline-start" />}创建待审视频项目</Button>{state.status !== "idle" ? <Alert variant={state.status === "error" ? "destructive" : "default"}><AlertTitle>{state.status === "success" ? "已保存" : "无法保存"}</AlertTitle><AlertDescription>{state.message}</AlertDescription></Alert> : null}</CardFooter></Card>}
    <Card><CardHeader><CardTitle>视频审核队列</CardTitle><CardDescription>以下记录只代表视频项目状态；未显示生成文件或公开链接。</CardDescription></CardHeader><CardContent>{entries.length === 0 ? <Empty><EmptyHeader><EmptyTitle>还没有视频项目</EmptyTitle><EmptyDescription>创建项目后会在这里等待 Gate 01 审核。</EmptyDescription></EmptyHeader></Empty> : <Table><TableHeader><TableRow><TableHead>产品</TableHead><TableHead>目标</TableHead><TableHead>平台</TableHead><TableHead>状态</TableHead><TableHead>审核</TableHead></TableRow></TableHeader><TableBody>{entries.map((entry) => <TableRow key={entry.id}><TableCell>{entry.productName}</TableCell><TableCell>{entry.objective}</TableCell><TableCell>{entry.platforms.join(" · ")}</TableCell><TableCell><Badge variant="secondary">{stateLabel(entry.state)}</Badge></TableCell><TableCell>{entry.approvalStatus ? <Badge variant={entry.approvalStatus === "approved" ? "default" : "outline"}>{entry.approvalStatus}</Badge> : "—"}</TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card>
  </div>;
}
