ALTER TABLE "product_media_asset" DROP CONSTRAINT "product_media_dimensions_positive";--> statement-breakpoint
ALTER TABLE "product_media_asset" DROP CONSTRAINT "product_media_technical_consistent";--> statement-breakpoint
ALTER TABLE "product_media_asset" DROP CONSTRAINT "product_media_review_consistent";--> statement-breakpoint
ALTER TABLE "product_media_asset" ADD CONSTRAINT "product_media_asset_rights_evidence_ref_evidence_id_fk" FOREIGN KEY ("rights_evidence_ref") REFERENCES "public"."evidence"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_media_asset" ADD CONSTRAINT "product_media_asset_review_evidence_ref_evidence_id_fk" FOREIGN KEY ("review_evidence_ref") REFERENCES "public"."evidence"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_media_asset" ADD CONSTRAINT "product_media_dimensions_bounded" CHECK ("product_media_asset"."width" between 1 and 32768 and "product_media_asset"."height" between 1 and 32768);--> statement-breakpoint
ALTER TABLE "product_media_asset" ADD CONSTRAINT "product_media_description_bounded" CHECK (length("product_media_asset"."description") <= 500);--> statement-breakpoint
ALTER TABLE "product_media_asset" ADD CONSTRAINT "product_media_review_notes_bounded" CHECK (length("product_media_asset"."review_notes") <= 1000);--> statement-breakpoint
ALTER TABLE "product_media_asset" ADD CONSTRAINT "product_media_tags_array" CHECK (jsonb_typeof("product_media_asset"."tags") = 'array');--> statement-breakpoint
ALTER TABLE "product_media_asset" ADD CONSTRAINT "product_media_technical_consistent" CHECK (("product_media_asset"."media_type" = 'image' and "product_media_asset"."duration_ms" is null and "product_media_asset"."fps" is null and not "product_media_asset"."has_audio") or ("product_media_asset"."media_type" = 'video' and "product_media_asset"."duration_ms" between 1 and 120000 and "product_media_asset"."fps" > 0 and "product_media_asset"."fps" <= 240));--> statement-breakpoint
ALTER TABLE "product_media_asset" ADD CONSTRAINT "product_media_review_consistent" CHECK (("product_media_asset"."review_status" = 'pending' and "product_media_asset"."reviewed_by" is null and "product_media_asset"."reviewed_at" is null and "product_media_asset"."review_evidence_ref" is null) or ("product_media_asset"."review_status" in ('approved', 'rejected') and "product_media_asset"."reviewed_by" is not null and "product_media_asset"."reviewed_at" is not null and "product_media_asset"."review_evidence_ref" is not null and length(btrim("product_media_asset"."review_evidence_ref")) > 0));