"use client";

import { startTransition, useActionState, useEffect, useRef, useState } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { BotIcon, CheckCircle2Icon, FileUpIcon, PlusIcon, RotateCcwIcon, ShieldCheckIcon, XCircleIcon } from "lucide-react";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Empty, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty";
import { Field, FieldDescription, FieldError, FieldGroup, FieldLabel, FieldLegend, FieldSet } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Spinner } from "@/components/ui/spinner";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { runProductAgentAction } from "@/lib/actions/product-agent";
import { createProductCatalogDraftAction, decideProductCatalogReviewAction, reviseProductCatalogDraftAction } from "@/lib/actions/products";
import { initialProductActionState, initialProductAgentActionState } from "@/lib/action-states";
import type { ProductAgentModelSettings } from "@/lib/ai/product-agent-model-config";
import { productAgentRunFormSchema, productCatalogFormSchema, productReviewFormSchema } from "@/lib/form-schemas";
import type { ProductCatalogDetail, ProductCatalogEntry } from "@/lib/products";
import { useWorkspaceDirty } from "./dirty-state";

const productTypes = [
  ["clutch_disc", "离合器片"], ["clutch_cover", "离合器盖 / 压盘"], ["release_bearing", "分离轴承"], ["clutch_kit", "离合器套件"],
] as const;
type ProductValues = z.infer<typeof productCatalogFormSchema>;
type ReviewValues = z.infer<typeof productReviewFormSchema>;
type AgentValues = z.infer<typeof productAgentRunFormSchema>;

const emptyProduct: ProductValues = { productName: "", productType: "clutch_disc", internalSku: "", oeNumbers: "", application: "", vehicleBrand: "", vehicleModel: "", clutchDiameterMm: "", splineCount: "", splineSize: "", frictionMaterial: "", sourceRef: "", evidenceRef: "" };

function stateLabel(state: string) {
  return ({ PRODUCT_REVIEW_REQUIRED: "待 Gate 01", PRODUCT_REVISION_REQUIRED: "待修订", PRODUCT_READY: "已核验" } as Record<string, string>)[state] ?? state;
}

function textValue(value: unknown) { return typeof value === "string" || typeof value === "number" ? String(value) : ""; }
function draftValues(detail: ProductCatalogDetail): ProductValues {
  const product = detail.draft.product; const specifications = detail.draft.specifications ?? {};
  return { productName: textValue(product.product_name), productType: (product.product_type as ProductValues["productType"]) ?? "clutch_disc", internalSku: textValue(product.internal_sku), oeNumbers: Array.isArray(product.oe_numbers) ? product.oe_numbers.filter((value): value is string => typeof value === "string").join(", ") : "", application: textValue(product.application), vehicleBrand: textValue(product.vehicle_brand), vehicleModel: textValue(product.vehicle_model), clutchDiameterMm: textValue(specifications.clutch_diameter_mm), splineCount: textValue(specifications.spline_count), splineSize: textValue(specifications.spline_size), frictionMaterial: textValue(specifications.friction_material), sourceRef: detail.draft.source_ref, evidenceRef: detail.draft.evidence_refs[0] ?? "" };
}

function ProductFields({ form }: { form: ReturnType<typeof useForm<ProductValues>> }) {
  return <FieldGroup>
    <Field data-invalid={!!form.formState.errors.productName}><FieldLabel htmlFor="product-name">产品名称</FieldLabel><Input id="product-name" aria-invalid={!!form.formState.errors.productName} {...form.register("productName")} /><FieldError errors={[form.formState.errors.productName]} /></Field>
    <Field data-invalid={!!form.formState.errors.productType}><FieldLabel>产品类型</FieldLabel><Controller control={form.control} name="productType" render={({ field }) => <Select items={Object.fromEntries(productTypes)} value={field.value} onValueChange={field.onChange}><SelectTrigger className="w-full" aria-invalid={!!form.formState.errors.productType}><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{productTypes.map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectGroup></SelectContent></Select>} /><FieldError errors={[form.formState.errors.productType]} /></Field>
    <Field data-invalid={!!form.formState.errors.internalSku}><FieldLabel htmlFor="internal-sku">内部编号</FieldLabel><Input id="internal-sku" aria-invalid={!!form.formState.errors.internalSku} {...form.register("internalSku")} /><FieldError errors={[form.formState.errors.internalSku]} /></Field>
    <Field><FieldLabel htmlFor="oe-numbers">OE / OEM 编号</FieldLabel><Input id="oe-numbers" placeholder="多个编号用逗号分隔" {...form.register("oeNumbers")} /></Field>
    <FieldSet><FieldLegend>适配信息</FieldLegend><FieldGroup><Field><FieldLabel htmlFor="application">适配说明</FieldLabel><Input id="application" {...form.register("application")} /></Field><Field><FieldLabel htmlFor="vehicle-brand">车辆品牌</FieldLabel><Input id="vehicle-brand" {...form.register("vehicleBrand")} /></Field><Field><FieldLabel htmlFor="vehicle-model">车型</FieldLabel><Input id="vehicle-model" {...form.register("vehicleModel")} /></Field></FieldGroup></FieldSet>
    <FieldSet><FieldLegend>离合器规格</FieldLegend><FieldDescription>没有来源依据时留空，AI 不能补齐。</FieldDescription><FieldGroup><Field data-invalid={!!form.formState.errors.clutchDiameterMm}><FieldLabel htmlFor="clutch-diameter">盘径（mm）</FieldLabel><Input id="clutch-diameter" inputMode="decimal" aria-invalid={!!form.formState.errors.clutchDiameterMm} {...form.register("clutchDiameterMm")} /><FieldError errors={[form.formState.errors.clutchDiameterMm]} /></Field><Field data-invalid={!!form.formState.errors.splineCount}><FieldLabel htmlFor="spline-count">花键数</FieldLabel><Input id="spline-count" inputMode="numeric" aria-invalid={!!form.formState.errors.splineCount} {...form.register("splineCount")} /><FieldError errors={[form.formState.errors.splineCount]} /></Field><Field><FieldLabel htmlFor="spline-size">花键尺寸</FieldLabel><Input id="spline-size" {...form.register("splineSize")} /></Field><Field><FieldLabel htmlFor="friction-material">摩擦材料</FieldLabel><Input id="friction-material" {...form.register("frictionMaterial")} /></Field></FieldGroup></FieldSet>
    <FieldSet><FieldLegend>来源与证据</FieldLegend><FieldGroup><Field data-invalid={!!form.formState.errors.sourceRef}><FieldLabel htmlFor="source-ref">来源引用</FieldLabel><Input id="source-ref" placeholder="source-catalog-001" aria-invalid={!!form.formState.errors.sourceRef} {...form.register("sourceRef")} /><FieldError errors={[form.formState.errors.sourceRef]} /></Field><Field data-invalid={!!form.formState.errors.evidenceRef}><FieldLabel htmlFor="evidence-ref">字段证据引用</FieldLabel><Input id="evidence-ref" placeholder="evidence-product-001" aria-invalid={!!form.formState.errors.evidenceRef} {...form.register("evidenceRef")} /><FieldError errors={[form.formState.errors.evidenceRef]} /></Field></FieldGroup></FieldSet>
  </FieldGroup>;
}

function ProductDraftForm({ projectId, detail }: { projectId: string; detail?: ProductCatalogDetail }) {
  const router = useRouter(); const revising = detail?.state === "PRODUCT_REVISION_REQUIRED";
  const [state, action, pending] = useActionState(revising ? reviseProductCatalogDraftAction : createProductCatalogDraftAction, initialProductActionState);
  const form = useForm<ProductValues>({ resolver: zodResolver(productCatalogFormSchema), defaultValues: detail ? draftValues(detail) : emptyProduct });
  useWorkspaceDirty(`product-draft-${detail?.id ?? "new"}`, form.formState.isDirty);
  useEffect(() => { if (state.status === "success") { form.reset(revising ? form.getValues() : emptyProduct); router.refresh(); } }, [form, revising, router, state.status]);
  function submit(values: ProductValues) { const data = new FormData(); data.set("projectId", projectId); if (detail) data.set("productId", detail.id); for (const [key, value] of Object.entries(values)) data.set(key, value); startTransition(() => action(data)); }
  return <Card><CardHeader><CardTitle>{revising ? "修订产品草稿" : "手动新建产品草稿"}</CardTitle><CardDescription>{revising ? "只更正有来源依据的字段，提交后重新进入 Gate 01。" : "保存后只创建待审核记录，不会直接成为 Product Ready。"}</CardDescription></CardHeader><CardContent><form id={revising ? "revise-product" : "create-product"} onSubmit={form.handleSubmit(submit)}><ProductFields form={form} /></form></CardContent><CardFooter className="flex-col items-stretch gap-3"><Button form={revising ? "revise-product" : "create-product"} type="submit" disabled={pending}>{pending ? <Spinner data-icon="inline-start" /> : revising ? <RotateCcwIcon data-icon="inline-start" /> : <PlusIcon data-icon="inline-start" />}{revising ? "提交修订并送审" : "创建待审核草稿"}</Button>{state.message ? <p className={state.status === "error" ? "text-sm text-destructive" : "text-sm text-muted-foreground"} aria-live="polite">{state.message}</p> : null}</CardFooter></Card>;
}

function ProductAgentForm({ projectId, modelConfigs }: { projectId: string; modelConfigs: ProductAgentModelSettings[] }) {
  const router = useRouter(); const fileRef = useRef<HTMLInputElement>(null); const [state, action, pending] = useActionState(runProductAgentAction, initialProductAgentActionState);
  const usableConfigs = modelConfigs.filter((item) => item.apiKeyConfigured || item.authTokenConfigured);
  const defaultConfig = usableConfigs.find((item) => item.isDefault) ?? usableConfigs[0];
  const emptyAgent = { modelConfigId: defaultConfig?.id ?? "", model: defaultConfig?.model ?? "", sourceRef: "", evidenceRef: "", sourceText: "", hasUpload: false };
  const form = useForm<AgentValues>({ resolver: zodResolver(productAgentRunFormSchema), defaultValues: emptyAgent });
  const choices = usableConfigs.flatMap((config) => Array.from(new Set([config.model, ...config.discoveredModels].map((model) => model.trim()).filter(Boolean))).map((model) => ({ value: JSON.stringify([config.id, model]), configId: config.id, model, label: `${config.name} · ${model}` })));
  const initialChoice = choices.find((choice) => choice.configId === emptyAgent.modelConfigId && choice.model === emptyAgent.model)?.value ?? "";
  const [selectedChoice, setSelectedChoice] = useState(initialChoice);
  useWorkspaceDirty("product-agent-import", form.formState.isDirty);
  useEffect(() => { if (state.status === "success") { form.reset(emptyAgent); setSelectedChoice(initialChoice); if (fileRef.current) fileRef.current.value = ""; router.refresh(); } }, [form, router, state.status]);
  function submit(values: AgentValues) { const data = new FormData(); data.set("projectId", projectId); data.set("modelConfigId", values.modelConfigId); data.set("model", values.model); data.set("sourceRef", values.sourceRef ?? ""); data.set("evidenceRef", values.evidenceRef ?? ""); data.set("sourceText", values.sourceText); const file = fileRef.current?.files?.[0]; if (file) data.set("document", file); startTransition(() => action(data)); }
  const choiceItems = Object.fromEntries(choices.map((choice) => [choice.value, choice.label]));
  return <Card><CardHeader><CardTitle>从获授权资料导入</CardTitle><CardDescription>选择已保存的 Provider 与模型，上传 PDF、CSV、XLS 或 XLSX，或粘贴已预处理文本；结果仍需 Gate 01。</CardDescription></CardHeader><CardContent><form id="product-agent-import" onSubmit={form.handleSubmit(submit)}><FieldGroup>{choices.length ? <Field data-invalid={!!form.formState.errors.modelConfigId || !!form.formState.errors.model}><FieldLabel>模型</FieldLabel><Select items={choiceItems} value={selectedChoice} onValueChange={(value) => { const choice = choices.find((item) => item.value === value); if (!choice) return; setSelectedChoice(choice.value); form.setValue("modelConfigId", choice.configId, { shouldValidate: true }); form.setValue("model", choice.model, { shouldValidate: true }); }}><SelectTrigger className="w-full" aria-label="模型" aria-invalid={!!form.formState.errors.modelConfigId || !!form.formState.errors.model}><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{choices.map((choice) => <SelectItem key={choice.value} value={choice.value}>{choice.label}</SelectItem>)}</SelectGroup></SelectContent></Select><FieldDescription>本次运行只使用这里选择的模型。</FieldDescription><FieldError errors={[form.formState.errors.modelConfigId, form.formState.errors.model]} /></Field> : null}<Field><FieldLabel htmlFor="agent-document">产品资料</FieldLabel><Input ref={fileRef} id="agent-document" type="file" accept=".pdf,.csv,.xls,.xlsx" onChange={(event) => form.setValue("hasUpload", Boolean(event.target.files?.length), { shouldValidate: true })} /><FieldDescription>原始文件只进入 Private Blob，最大 25MB。</FieldDescription></Field><Field data-invalid={!!form.formState.errors.sourceRef}><FieldLabel htmlFor="agent-source">来源引用</FieldLabel><Input id="agent-source" placeholder="source-catalog-001" {...form.register("sourceRef")} /><FieldError errors={[form.formState.errors.sourceRef]} /></Field><Field data-invalid={!!form.formState.errors.evidenceRef}><FieldLabel htmlFor="agent-evidence">字段证据引用</FieldLabel><Input id="agent-evidence" placeholder="evidence-catalog-001" {...form.register("evidenceRef")} /><FieldError errors={[form.formState.errors.evidenceRef]} /></Field><Field data-invalid={!!form.formState.errors.sourceText}><FieldLabel htmlFor="agent-text">已授权资料文本</FieldLabel><Textarea id="agent-text" rows={8} {...form.register("sourceText")} /><FieldError errors={[form.formState.errors.sourceText]} /></Field></FieldGroup></form></CardContent><CardFooter className="flex-col items-stretch gap-3"><Button form="product-agent-import" type="submit" disabled={pending || choices.length === 0}>{pending ? <Spinner data-icon="inline-start" /> : <BotIcon data-icon="inline-start" />}生成待审核草稿</Button>{choices.length === 0 ? <p className="text-sm text-muted-foreground">管理员需先在工作区设置中保存至少一个可用模型。</p> : null}{state.message ? <p className={state.status === "error" ? "text-sm text-destructive" : "text-sm text-muted-foreground"} aria-live="polite">{state.message}</p> : null}</CardFooter></Card>;
}

function ProductReview({ projectId, detail, canReview }: { projectId: string; detail: ProductCatalogDetail; canReview: boolean }) {
  const router = useRouter(); const [state, action, pending] = useActionState(decideProductCatalogReviewAction, initialProductActionState);
  const form = useForm<ReviewValues>({ resolver: zodResolver(productReviewFormSchema), defaultValues: { productId: detail.id, decision: "approved", evidenceRef: "", notes: "" } });
  useWorkspaceDirty(`product-review-${detail.id}`, form.formState.isDirty);
  useEffect(() => { if (state.status === "success") { form.reset(form.getValues()); router.refresh(); } }, [form, router, state.status]);
  function submit(values: ReviewValues) { const data = new FormData(); data.set("projectId", projectId); for (const [key, value] of Object.entries(values)) data.set(key, value); startTransition(() => action(data)); }
  const facts = (["product", "specifications", "commercial"] as const).flatMap((section) => Object.entries(detail.draft[section] ?? {}).map(([field, value]) => ({ path: `${section}.${field}`, value: Array.isArray(value) ? value.join(", ") : textValue(value), evidence: detail.draft.field_evidence[`${section}.${field}`] ?? "缺失" })));
  const canDecide = canReview && detail.state === "PRODUCT_REVIEW_REQUIRED" && detail.approvalStatus === "pending";
  return <div className="flex flex-col gap-4"><div className="flex flex-wrap gap-2"><Badge variant="secondary">{stateLabel(detail.state)}</Badge><Badge variant="outline">{detail.internalSku}</Badge></div><Card><CardHeader><CardTitle>产品事实与证据</CardTitle><CardDescription>逐项核对，不能用视觉猜测替代来源。</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>字段</TableHead><TableHead>当前值</TableHead></TableRow></TableHeader><TableBody>{facts.map((fact) => <TableRow key={fact.path}><TableCell className="max-w-36 whitespace-normal break-words"><span className="font-mono text-xs">{fact.path}</span><span className="mt-1 block text-xs text-muted-foreground">{fact.evidence}</span></TableCell><TableCell className="max-w-48 whitespace-normal break-words">{fact.value || "未提供"}</TableCell></TableRow>)}</TableBody></Table></CardContent><CardFooter>阻塞项：{detail.blockingFields.length ? detail.blockingFields.join("、") : "无自动阻塞项，仍需人工核对。"}</CardFooter></Card>{canDecide ? <Card><CardHeader><CardTitle>Gate 01 决定</CardTitle><CardDescription>批准不会发布、报价或承诺交期。</CardDescription></CardHeader><CardContent><form id="product-review" onSubmit={form.handleSubmit(submit)}><FieldGroup><Field><FieldLabel>决定</FieldLabel><Controller control={form.control} name="decision" render={({ field }) => <Select items={{ approved: "批准事实", rejected: "退回修订" }} value={field.value} onValueChange={field.onChange}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="approved">批准事实</SelectItem><SelectItem value="rejected">退回修订</SelectItem></SelectGroup></SelectContent></Select>} /></Field><Field data-invalid={!!form.formState.errors.evidenceRef}><FieldLabel htmlFor="product-review-evidence">审核证据</FieldLabel><Input id="product-review-evidence" placeholder="evidence-review-001" {...form.register("evidenceRef")} /><FieldError errors={[form.formState.errors.evidenceRef]} /></Field><Field><FieldLabel htmlFor="product-review-notes">审核备注</FieldLabel><Textarea id="product-review-notes" {...form.register("notes")} /></Field></FieldGroup></form></CardContent><CardFooter className="flex-col items-stretch gap-3"><Button form="product-review" type="submit" disabled={pending}>{pending ? <Spinner data-icon="inline-start" /> : form.watch("decision") === "approved" ? <CheckCircle2Icon data-icon="inline-start" /> : <XCircleIcon data-icon="inline-start" />}提交人工决定</Button>{state.message ? <p className="text-sm text-muted-foreground" aria-live="polite">{state.message}</p> : null}</CardFooter></Card> : <Alert><ShieldCheckIcon /><AlertTitle>{canReview ? "当前无需审核" : "等待管理员审核"}</AlertTitle><AlertDescription>业务员可以核对事实，但不能替代管理员作出 Gate 01 决定。</AlertDescription></Alert>}{detail.state === "PRODUCT_REVISION_REQUIRED" ? <ProductDraftForm projectId={projectId} detail={detail} /> : null}</div>;
}

export function ProductPanel({ projectId, entries, detail, canReview, agentModelConfigs }: { projectId: string; entries: ProductCatalogEntry[]; detail: ProductCatalogDetail | null; canReview: boolean; agentModelConfigs: ProductAgentModelSettings[] }) {
  const pathname = usePathname(); const searchParams = useSearchParams(); const [tab, setTab] = useState(detail ? "records" : "agent");
  function href(item: string) { const params = new URLSearchParams(searchParams.toString()); params.set("panel", "product"); params.set("item", item); return `${pathname}?${params}`; }
  return <div className="flex flex-col gap-4"><div><div className="flex flex-wrap gap-2"><Badge variant="secondary">产品资料</Badge><Badge variant="outline">Gate 01 受控</Badge></div><p className="mt-2 text-sm text-muted-foreground">导入、录入、审核和修订都在当前营销项目中完成。</p></div><Tabs value={tab} onValueChange={setTab}><TabsList className="w-full"><TabsTrigger value="agent"><FileUpIcon />智能导入</TabsTrigger><TabsTrigger value="manual"><PlusIcon />手动录入</TabsTrigger><TabsTrigger value="records">记录 {entries.length}</TabsTrigger></TabsList><TabsContent value="agent"><ProductAgentForm projectId={projectId} modelConfigs={agentModelConfigs} /></TabsContent><TabsContent value="manual"><ProductDraftForm projectId={projectId} /></TabsContent><TabsContent value="records"><div className="flex flex-col gap-3">{entries.length ? entries.map((entry) => <Button key={entry.id} render={<Link href={href(entry.id)} />} variant={detail?.id === entry.id ? "secondary" : "outline"} className="h-auto justify-start py-3 text-left"><span className="flex min-w-0 flex-1 flex-col gap-1"><span className="truncate font-medium">{entry.internalSku} · {entry.productName}</span><span className="text-xs text-muted-foreground">{stateLabel(entry.state)}{entry.blockingFields.length ? ` · ${entry.blockingFields.length} 个阻塞项` : ""}</span></span></Button>) : <Empty><EmptyHeader><EmptyMedia variant="icon"><FileUpIcon /></EmptyMedia><EmptyTitle>当前项目还没有产品</EmptyTitle><EmptyDescription>从智能导入或手动录入开始。</EmptyDescription></EmptyHeader></Empty>}{detail ? <ProductReview projectId={projectId} detail={detail} canReview={canReview} /> : null}</div></TabsContent></Tabs></div>;
}
