import { randomUUID } from "node:crypto";

import { put } from "@vercel/blob";
import { z } from "zod";

import { getDatabase, type Database } from "@/lib/db/client";
import { videoGeneratedAsset } from "@/lib/db/schema";
import { safeEvidencePathSegment } from "@/lib/evidence/store";

import type { PrivateVideoAssetStore } from "./ai-sdk-adapters";
import type { VideoProviderId } from "./provider-capabilities";

export const generatedVideoInputSchema = z.object({
  data: z.instanceof(Uint8Array).refine((value) => value.byteLength > 0, "生成视频不能为空。"),
  contentType: z.string().trim().regex(/^video\/[a-z0-9.+-]+$/i, "生成资产必须是视频 MIME 类型。"),
  provider: z.string().trim().min(1).max(120),
  modelId: z.string().trim().min(1).max(240),
});

/**
 * Saves generated bytes privately and returns only an opaque asset reference.
 * The backing Blob pathname is recorded server-side and never returned here.
 */
export class VercelPrivateVideoAssetStore implements PrivateVideoAssetStore {
  constructor(private readonly database: Database = getDatabase()) {}

  async putGeneratedVideo(input: { data: Uint8Array; contentType: string; provider: VideoProviderId; modelId: string }): Promise<string> {
    const value = generatedVideoInputSchema.parse(input);
    const assetRef = `asset-${randomUUID()}`;
    const pathname = `video/generated/${safeEvidencePathSegment(value.provider)}/${safeEvidencePathSegment(value.modelId)}/${assetRef}.mp4`;
    const result = await put(pathname, new Blob([value.data], { type: value.contentType }), {
      access: "private",
      addRandomSuffix: false,
      contentType: value.contentType,
      token: process.env.BLOB_READ_WRITE_TOKEN,
    });
    await this.database.insert(videoGeneratedAsset).values({
      assetRef,
      blobPath: result.pathname,
      contentType: value.contentType,
      sizeBytes: value.data.byteLength,
      provider: value.provider,
      modelId: value.modelId,
    });
    return assetRef;
  }
}
